In [4]:
import os
import re
import numpy as np
import torch
path = "C:/Users/w9714/Desktop/Nando lab/VRT-data/requests" 
files= os.listdir(path) 
s = []
for file in files: 
          f = open(path+"/"+file); 
          iter_f = iter(f);
          str = ""
          for line in iter_f: 
              str = str + line
          s.append(str) 
a="".join(s)

In [5]:
pattern = re.compile(r'(?<="lat": )\d+\.?\d*')
b=pattern.findall(a)
b_float = []
for num in b:
    b_float.append(float(num))
b_float

[40.74650192260742,
 40.75445175170898,
 40.75325012207031,
 40.75041961669922,
 40.76206970214844,
 40.77000045776367,
 40.77781677246094,
 40.7667350769043,
 40.73418045043945,
 40.75478744506836,
 40.74371337890625,
 40.76704025268555,
 40.70808792114258,
 40.72240829467773,
 40.78036880493164,
 40.76415252685547,
 40.7509765625,
 40.81673049926758,
 40.78062057495117,
 40.789566040039055,
 40.73945617675781,
 40.727195739746094,
 40.76388931274415,
 40.77878189086913,
 40.756141662597656,
 40.78266906738281,
 40.77012252807617,
 40.77509689331055,
 40.75654983520508,
 40.738807678222656,
 40.74158477783203,
 40.74856185913085,
 40.7601318359375,
 40.74892044067383,
 40.75200653076172,
 40.73565673828125,
 40.76433563232422,
 40.769142150878906,
 40.75918960571289,
 40.7307014465332,
 40.75839614868164,
 40.77744674682617,
 40.764663696289055,
 40.754070281982415,
 40.78405380249024,
 40.77020263671875,
 40.77112197875977,
 40.75826644897461,
 40.74874114990234,
 40.7297248840332,
 

In [6]:
pattern = re.compile(r'(?<="lon": -)\d+\.?\d*')
c=pattern.findall(a)
c_float = []
for num in c:
    c_float.append(float(num))
c_float

[73.9815902709961,
 73.97826385498048,
 73.9737777709961,
 73.99189758300781,
 73.9661636352539,
 73.96096038818358,
 73.95130157470702,
 73.98320770263672,
 73.98978424072266,
 73.97167205810547,
 74.00707244873048,
 73.98759460449219,
 74.00626373291014,
 73.98313140869139,
 73.9592056274414,
 73.9690933227539,
 73.9939956665039,
 73.96078491210938,
 73.97626495361328,
 73.97716522216798,
 73.99212646484375,
 74.00675964355469,
 73.96906280517578,
 73.98651885986328,
 73.96141815185547,
 73.95748138427734,
 73.9914321899414,
 73.98785400390625,
 73.9976806640625,
 73.9874496459961,
 73.99368286132812,
 73.98863983154298,
 73.96472930908203,
 73.97767639160156,
 73.97722625732422,
 73.99374389648438,
 73.97271728515625,
 73.98858642578125,
 73.96533203125,
 73.98296356201173,
 73.97087860107422,
 73.96060943603516,
 73.97687530517578,
 73.9802474975586,
 73.95440673828125,
 73.9805679321289,
 73.97964477539062,
 73.97676849365234,
 74.00687408447266,
 74.00505828857422,
 73.9539489746

In [7]:
b_around=np.around(b_float, decimals=3)
b_around.shape

(199902,)

In [8]:
c_around=np.around(c_float, decimals=3)
c_around.shape

(199902,)

In [9]:
b_ = np.reshape(b_around, (199902,1))
c_ = np.reshape(c_around, (199902,1))
stack=np.concatenate((c_,b_),axis=1)
stack.shape

(199902, 2)

In [10]:
#seperate O$D
O_lon=[]
O_lat=[]
D_lon=[]
D_lat=[]
for i in range(199902):
    if i % 2 == 0:
        O_lon.append(stack[i,0])
        O_lat.append(stack[i,1])
for i in range(199902):
    if i % 2 == 1:
        D_lon.append(stack[i,0])
        D_lat.append(stack[i,1])

In [11]:
stack

array([[73.982, 40.747],
       [73.978, 40.754],
       [73.974, 40.753],
       ...,
       [73.984, 40.762],
       [73.985, 40.722],
       [73.994, 40.732]])

In [12]:
print(max(O_lon),min(O_lon),max(O_lat),min(O_lat))

74.018 73.913 40.873 40.701


In [13]:
print(max(D_lon),min(D_lon),max(D_lat),min(D_lat))

74.018 73.913 40.874 40.701


In [14]:
#Origin
#according to the whole vehicle&Od data to determin the min:lat=40.701,min:lon=73.911
#all 99951
#read 1000 one time
x0=[]
x1=[]
for i in range(1000):
    x0.append((O_lon[i]-73.911)*1000)
    x1.append((O_lat[i]-40.701)*1000) 

In [15]:
x0=np.around(x0)
x1=np.around(x1)
x0_= np.reshape(x0, (1000,1))
x1_= np.reshape(x1, (1000,1))
x=np.concatenate((x0_,x1_),axis=1)
x=np.int_(x)
x

array([[69, 46],
       [61, 52],
       [53, 61],
       ...,
       [84, 25],
       [81, 50],
       [46, 71]])

In [16]:
O=np.zeros((1000,200,200),dtype=int)
for i in range(1000):
    O[i,x[i,0],x[i,1]]=1
O.shape
O=torch.from_numpy(O)

(1000, 200, 200)

In [20]:
#Destination
y0=[]
y1=[]
for i in range(1000):
    y0.append((D_lon[i]-73.911)*1000)
    y1.append((D_lat[i]-40.701)*1000)
y0=np.around(y0)
y1=np.around(y1)
y0_= np.reshape(y0, (1000,1))
y1_= np.reshape(y1, (1000,1))
y=np.concatenate((y0_,y1_),axis=1)
y=np.int_(y)
y

array([[65, 53],
       [79, 49],
       [48, 69],
       ...,
       [94, 10],
       [60, 87],
       [99,  4]])

In [23]:
D=np.zeros((1000,200,200),dtype=int)
for i in range(1000):
    D[i,y[i,0],y[i,1]]=1
D.shape
D=torch.from_numpy(D)